#!/sbin/busybox sh

if [ "a$2" != "a" ];then
	filename=zzmoove_$(basename $2)

	if [ "a$3" == "a" ];then
	  evalcmd='eval "echo \$$filename"'
	  if [ "a`eval $evalcmd`" == "a" ]; then
	    eval $filename=`cat $2`
	  fi
	  eval $evalcmd
	else
	  evalcmd='eval "$filename=$3"'
	  eval $evalcmd
	  evalcmd='eval "echo \$$filename"'
	  if [ "$CONTROLSWITCH_ZZMOOVE" == "on" -o "$CONFIG_BOOTING" != "1" ]; then
		  if [ -f $2 ];then
		    echo $3 > $2
		    eval $filename=`cat $2`
		  fi
	  fi
	  eval $evalcmd
	fi
fi



