#!/sbin/busybox sh

if [ "a$2" != "a" ];then
	filename=zzmoove_$(basename $2)
	evalcmd='eval "echo \$$filename"'
	if [ "$scaling_governor" == "zzmoove" ];then
		if [ "$CONTROLSWITCH_ZZMOOVE" == "on" -o "$CONFIG_BOOTING" != "1" ]; then
        		eval $evalcmd > $2
		fi
	fi
	eval $evalcmd
fi



